/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui {
	import laya.ui.*;
	import laya.display.*;
	import TestMC;

	public class TestMCUI extends Scene {
		public var t1:Label;
		public var t2:Label;
		public var suan:Sprite;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("TestMC");

		}

	}
}